require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.cmp")
require("user.lsp")
require("user.treesitter")
require("user.telescope")
require("user.autopairs")
require("user.gitsigns")
vim.cmd("colorscheme nord")
