#!/bin/bash 

export PATH="${PATH}:$HOME/.config/bspwm/bin"
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors


## Configurations -------------------------------#
#bspc monitor -d 'ﲵ' '' '阮' 'ﭮ' ''
bspc monitor eDP -d 1 2 3 4 5 
bspc monitor HDMI-A-0 -d 6 7 8 9
bspc config border_width 1
bspc config window_gap 20
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# Special rules
bspc rule -a alacritty-float state=floating follow=on focus=on
bspc rule -a Pcmanfm state=floating follow=on focus=on
bspc rule -a Onboard state=floating follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Nm-connection-editor state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Nitrogen state=floating follow=on focus=on


# Autostart 

killall -9 sxhkd dunst 

dunst \
-geom "280x50-10+38" -frame_width "1" -font "Nerd Font Hack Regular 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

sxhkd &
~/.config/polybar/launch.sh &
nitrogen --restore
# Fix cursor
xsetroot -cursor_name left_ptr
