#!/usr/bin/env bash

## own stuff

picom &
wal -R -q  
id=$(xinput | grep "Touch[pP]ad.*id=\S\+\s" | grep -o "id=[0-9][0-9]") && id=${id:3}
xinput set-prop $id "libinput Tapping Enabled" 1

hc() {
    herbstclient "$@"
}

herbstclient emit_hook reload

xsetroot -solid "#5A8E3A"

herbstclient keyunbind --all
Mod=Mod4
hc keybind $Mod-Ctrl-q quit
hc keybind $Mod-Ctrl-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Alt-w spawn firefox
hc keybind $Mod-Return spawn alacritty
herbstclient keybind XF86AudioRaiseVolume spawn volume.sh up
herbstclient keybind XF86AudioLowerVolume spawn volume.sh down 
herbstclient keybind XF86AudioMute spawn volume.sh mute 


# basic movements
herbstclient keybind $Mod-h     focus left
herbstclient keybind $Mod-j     focus down
herbstclient keybind $Mod-k     focus up
herbstclient keybind $Mod-l     focus right

#moving clients in tiling and floating mode
herbstclient keybind $Mod-Shift-h     shift left
herbstclient keybind $Mod-Shift-j     shift down
herbstclient keybind $Mod-Shift-k     shift up
herbstclient keybind $Mod-Shift-l     shift right
# splitting frames

herbstclient keybind $Mod-u split   bottom  0.5
herbstclient keybind $Mod-Shift-u split   top  0.5
herbstclient keybind $Mod-o split   right   0.5
herbstclient keybind $Mod-Shift-o split   left   0.5

# let the current frame explode into subframes
herbstclient keybind $Mod-i split explode

tag_keys=( {1..9} 0 )

if [ -f "$HOME/.config/herbstluftwm/hl-tags" ]; then tag_names=( $(cat $HOME/.config/herbstluftwm/hl-tags) ); else tag_names=( {1..9} ); fi

herbstclient rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
  herbstclient add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if [ -n "$key" ] ; then
    herbstclient keybind "$Mod-$key" use_index "$i"
    herbstclient keybind "$Mod-Shift-$key" move_index "$i"
    fi
  done

herbstclient keybind $Mod+dead_circumflex spawn $HOME/.local/scripts/hl-tagman -j
herbstclient keybind $Mod+Shift+dead_circumflex spawn $HOME/.local/scripts/hl-tagman -m

# cycle through tags
herbstclient keybind $Mod-period use_index +1 
herbstclient keybind $Mod-comma  use_index -1 


# layouting
herbstclient keybind $Mod-r remove
herbstclient keybind $Mod-s floating toggle

herbstclient keybind $Mod-Shift-s spawn $HOME/.local/scripts/toggle-screenkey 

herbstclient keybind $Mod-f fullscreen toggle
herbstclient keybind $Mod-Shift-f set_attr clients.focus.floating toggle
herbstclient keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
herbstclient keybind $Mod-Space  \
	or , and . compare tags.focus.curframe_wcount = 2  \
			. cycle_layout +1 vertical max horizontal \
			, cycle_layout +1 grid max
			
herbstclient keybind $Mod-g set frame_border_width 2
herbstclient keybind $Mod-Shift-g set frame_border_width 0

herbstclient keybind $Mod-w set window_border_width 2
herbstclient keybind $Mod-Shift-w set window_border_width 0

# herbstclient keybind $Mod-h cycle_value frame_gap 0 1 2 5 10 20 50 100 200
# herbstclient keybind $Mod-Shift-h cycle_value frame_gap 200 100 50 20 10 5 2 1 0

# herbstclient keybind $Mod-j cycle_value window_gap 0 1 2 5 10 20 50 100 200
# herbstclient keybind $Mod-Shift-j cycle_value window_gap 200 100 50 20 10 5 2 1 0

herbstclient keybind $Mod-b set_attr theme.title_height 20
herbstclient keybind $Mod-Shift-b set_attr theme.title_height 0

herbstclient pad 0 0 0 20 0
herbstclient set auto_detect_panels 0
herbstclient set hide_covered_windows 1
herbstclient set always_show_frame 1
#herbstclient set frame_bg_transparent 1
herbstclient set frame_padding 0
herbstclient set mouse_recenter_gap 0


herbstclient mouseunbind --allscroll wheel up
herbstclient mousebind $Mod-Button1 move
herbstclient mousebind $Mod-Button2 zoom
herbstclient mousebind $Mod-Button3 resize

# focus
herbstclient keybind $Mod-BackSpace   cycle_monitor
herbstclient keybind $Mod-Tab         cycle_all +1
herbstclient keybind $Mod-Shift-Tab   cycle_all -1
herbstclient keybind $Mod-c cycle
herbstclient keybind $Mod-Shift-i jumpto urgent

herbstclient set smart_window_surroundings false
herbstclient set smart_frame_surroundings true
herbstclient attr theme.title_height 0
herbstclient attr theme.tiling.reset 1
herbstclient set frame_transparent_width 0

herbstclient set frame_border_width 0
herbstclient set frame_gap 8
herbstclient set window_border_width 1 
herbstclient set window_gap 2 

herbstclient set frame_padding 0
herbstclient set mouse_recenter_gap 0
. ${HOME}/.config/herbstluftwm/hl-theme
herbstclient set_attr theme.title_font hack-16


herbstclient unrule -F
#herbstclient rule class=XTerm tag=3 # move all xterms to tag 3
herbstclient rule focus=on # normally focus new clients
herbstclient rule floatplacement=center
# give focus to most common terminals
#herbstclient rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off



herbstclient set tree_style '╾│ ├└╼─┐'

hc unlock

hc detect_monitors

# setup panel 
{
    pids=( )
    # reserve some space for the panel on monitor 0
    hc pad 0 15 "" "" ""
    hc pad 1 15 "" "" ""

    # start the panel itself and remember its pid
    $HOME/.config/polybar/launch.sh &
    #xfce4-panel -d --sm-client-disable &
    pids+=( $! )
    # or start another panel:
    # mypanel &
    # pids+=( $! )
    # wait until the panels should be stopped
    herbstclient -w '(quit_panel|reload)'
    # stopp all started panels
    kill ${pids[@]}
} &

